pre_train: false

model: "AttentionUNet"
loss: "Dice"
optimizer: "Adam"
metric: "Dice"

in_channels: 3
out_channels: 1
batch_size: 32
epochs: 1
patience: 1
scheduler_patience: 1
learning_rate: 1e-5
save_model_path: "models_weights/{}_fold/model.pth"

n_inference: 1
name: "AUNet_D"
# test