pre_train: false

model: "AttentionUNet"
loss: "Dice"
optimizer: "Adam"
metric: "Dice"

in_channels: 3
out_channels: 1
batch_size: 32
epochs: 100
patience: 100
scheduler_patience: 100
learning_rate: 1e-5 #1e-5だと学習曲線が評価曲線を超えない100epochで
save_model_path: "models_weights/{}_fold/model.pth"

n_inference: 1
name: "AUNet_D"
# test