pre_train: false

model: "DeepLabV3"
backbone: "resnet101"
loss: "Dice"
optimizer: "Adam"
metric: "Dice"

in_channels: 3
out_channels: 1
batch_size: 32
epochs: 50
patience: 50
scheduler_patience: 50
learning_rate: 1e-4
save_model_path: "models_weights/{}_fold/model.pth"

name: "DLV3RN101_D"